FROM golang:1.23-alpine

ENV CGO_ENABLED=0
ENV GOOS=linux
ENV GO111MODULE=on

RUN mkdir -p /app
ENV XDIR=/app
ENV XKEY=CI_SECRET

RUN apk add --no-cache git
RUN apk --no-cache add ca-certificates
RUN apk add --no-cache bash

COPY . /app
WORKDIR /app

COPY go.mod /app
COPY go.sum /app

RUN go mod download