kind: Secret
apiVersion: v1
metadata:
  name: gitlab-pull-secret
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICAgImF1dGhzIjogewogICAgICAgICJyZWdpc3RyeS5naXRsYWIuY29tIjp7CiAgICAgICAgICAgICJ1c2VybmFtZSI6ImluZm8udGVycmFjZWl0IiwKICAgICAgICAgICAgInBhc3N3b3JkIjoiZ2xwYXQtc01TOGs5NU5FVFVHeG02c3VldlgiLAogICAgICAgICAgICAiYXV0aCI6ImFXNW1ieTUwWlhKeVlXTmxhWFE2WjJ4d1lYUXRjMDFUT0dzNU5VNUZWRlZIZUcwMmMzVmxkbGc9IgogICAgICAgIH0KICAgIH0KfSA=    
